services:
  site-calmmyself:
    image: nginx:alpine
    container_name: site-calmmyself
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - proxy
networks:
  proxy:
    external: true