version: '3.8'

services:
  calmmyself:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calmmyself-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - calmmyself-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next/cache

  # Optional: Add nginx reverse proxy for SSL termination and caching
  nginx:
    image: nginx:alpine
    container_name: calmmyself-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - calmmyself
    networks:
      - calmmyself-network
    security_opt:
      - no-new-privileges:true

networks:
  calmmyself-network:
    driver: bridge
    name: calmmyself-network

volumes:
  nginx-cache:
    name: calmmyself-nginx-cache